In [1]:
from polars import DataFrame, col, when, lit
from collections import namedtuple
from polars import Int32

In [2]:
Tx = namedtuple("Tx", ("ts", "price", "qty"))
txs = [
    Tx(1, 100.0, 10.0),
    Tx(2, 101.0, -2.0),
    Tx(3, 102.0, 2.0),
    Tx(4, 103.0, -10.0),
    Tx(5, 104.0, 5.0),
    Tx(6, 105.0, 5.0),
    Tx(7, 106.0, -10.0),
    Tx(8, 107.0, 3.0),
    Tx(9, 108.0, 3.0),
]

In [3]:
def self_enrich_txs(txs: list[any]) -> DataFrame:
    price = col("price")
    qty = col("qty")
    running_qty = col("running_qty")
    stretch = col("stretch")
    running_avg_price = col("running_avg_price")

    running_buy_only_cost = (
        when(qty > 0).then(qty * price).otherwise(0).cum_sum().over(stretch)
    )
    running_buy_only_qty = when(qty > 0).then(qty).otherwise(0).cum_sum().over(stretch)

    df = DataFrame(txs)
    df = (
        df.with_columns(running_qty=qty.cum_sum())
        .with_columns(
            stretch=(running_qty <= 0).shift(1).cast(Int32).cum_sum().fill_null(0),
        )
        .with_columns(
            running_cost=when(running_qty <= 0)
            .then(lit(0))
            .otherwise((qty * price).cum_sum().over(stretch)),
        )
        .with_columns(
            running_avg_price=(running_buy_only_cost / running_buy_only_qty).fill_nan(0)
        )
        .with_columns(
            realized_pnl=when(qty < 0)
            .then((price - running_avg_price) * -qty)
            .otherwise(None),
            cost=qty * running_avg_price,
        )
    )
    return df


self_enrich_txs(txs)

shape: (9, 9)
┌─────┬───────┬───────┬─────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ ts  ┆ price ┆ qty   ┆ running_qty ┆ … ┆ running_cost ┆ running_avg_ ┆ realized_pnl ┆ cost        │
│ --- ┆ ---   ┆ ---   ┆ ---         ┆   ┆ ---          ┆ price        ┆ ---          ┆ ---         │
│ i64 ┆ f64   ┆ f64   ┆ f64         ┆   ┆ f64          ┆ ---          ┆ f64          ┆ f64         │
│     ┆       ┆       ┆             ┆   ┆              ┆ f64          ┆              ┆             │
╞═════╪═══════╪═══════╪═════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 1   ┆ 100.0 ┆ 10.0  ┆ 10.0        ┆ … ┆ 1000.0       ┆ 100.0        ┆ null         ┆ 1000.0      │
│ 2   ┆ 101.0 ┆ -2.0  ┆ 8.0         ┆ … ┆ 798.0        ┆ 100.0        ┆ 2.0          ┆ -200.0      │
│ 3   ┆ 102.0 ┆ 2.0   ┆ 10.0        ┆ … ┆ 1002.0       ┆ 100.333333   ┆ null         ┆ 200.666667  │
│ 4   ┆ 103.0 ┆ -10.0 ┆ 0.0         ┆ … ┆ 0.0          ┆ 100.333333   ┆ 26.666667    ┆ -1003.33333 │
│     ┆       ┆       ┆             ┆   ┆              ┆              ┆              ┆ 3           │
│ 5   ┆ 104.0 ┆ 5.0   ┆ 5.0         ┆ … ┆ 520.0        ┆ 104.0        ┆ null         ┆ 520.0       │
│ 6   ┆ 105.0 ┆ 5.0   ┆ 10.0        ┆ … ┆ 1045.0       ┆ 104.5        ┆ null         ┆ 522.5       │
│ 7   ┆ 106.0 ┆ -10.0 ┆ 0.0         ┆ … ┆ 0.0          ┆ 104.5        ┆ 15.0         ┆ -1045.0     │
│ 8   ┆ 107.0 ┆ 3.0   ┆ 3.0         ┆ … ┆ 321.0        ┆ 107.0        ┆ null         ┆ 321.0       │
│ 9   ┆ 108.0 ┆ 3.0   ┆ 6.0         ┆ … ┆ 645.0        ┆ 107.5        ┆ null         ┆ 322.5       │
└─────┴───────┴───────┴─────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [4]:
from polars import Float64, Int64

def condsolidate_txs(
    txs: list,
    *,
    period_start_ts:float,
    period_start_price:float,
) -> DataFrame:
    TXs = DataFrame(txs)
    before = TXs.filter(col("ts") <= period_start_ts)
    after = TXs.filter(col("ts") > period_start_ts)

    before = before.select(
        ts=lit(period_start_ts).cast(Int64),
        price=lit(period_start_price).cast(Float64),
        qty=col("qty").sum(),
    ).tail(1)

    return before.extend(after)

In [5]:
from polars import Config


def calc_returns(txs: list, period_start_ts:int, period_start_price:float, market_price:float,) :
    enriched_txs = self_enrich_txs(txs)
    realized_pnl = enriched_txs.select(col("realized_pnl").fill_null(0).sum()).get_column('realized_pnl').first()
    last_stretch = enriched_txs.filter(col('stretch') == col('stretch').max()).select(
        col('ts'),
        col('price'),
        col('qty'),
    )
    consolidated = condsolidate_txs(last_stretch, period_start_ts=period_start_ts, period_start_price=period_start_price)
    enriched_txs = self_enrich_txs(consolidated).with_columns(
        unrealized_pnl=when(col('qty')>0).then(market_price*col('qty')-col('cost'))
    )
    unrealized_pnl, cost = enriched_txs.select(
        col("unrealized_pnl").fill_null(0).sum(),
        col('cost').last()).to_dicts()[0].values()

    with Config(tbl_cols=-1):
        print(enriched_txs)

    return realized_pnl, unrealized_pnl, unrealized_pnl/cost if cost !=0 else None

In [6]:
calc_returns(txs, 7, 100, 109)

shape: (3, 10)
┌─────┬───────┬─────┬────────────┬─────────┬───────────┬───────────┬───────────┬───────┬───────────┐
│ ts  ┆ price ┆ qty ┆ running_qt ┆ stretch ┆ running_c ┆ running_a ┆ realized_ ┆ cost  ┆ unrealize │
│ --- ┆ ---   ┆ --- ┆ y          ┆ ---     ┆ ost       ┆ vg_price  ┆ pnl       ┆ ---   ┆ d_pnl     │
│ i64 ┆ f64   ┆ f64 ┆ ---        ┆ i32     ┆ ---       ┆ ---       ┆ ---       ┆ f64   ┆ ---       │
│     ┆       ┆     ┆ f64        ┆         ┆ f64       ┆ f64       ┆ f64       ┆       ┆ f64       │
╞═════╪═══════╪═════╪════════════╪═════════╪═══════════╪═══════════╪═══════════╪═══════╪═══════════╡
│ 7   ┆ 100.0 ┆ 0.0 ┆ 0.0        ┆ 0       ┆ 0.0       ┆ 0.0       ┆ null      ┆ 0.0   ┆ null      │
│ 8   ┆ 107.0 ┆ 3.0 ┆ 3.0        ┆ 1       ┆ 321.0     ┆ 107.0     ┆ null      ┆ 321.0 ┆ 6.0       │
│ 9   ┆ 108.0 ┆ 3.0 ┆ 6.0        ┆ 1       ┆ 645.0     ┆ 107.5     ┆ null      ┆ 322.5 ┆ 4.5       │
└─────┴───────┴─────┴────────────┴─────────┴───────────┴───────────┴───────────┴───────┴───────────┘

(43.666666666666714, 10.5, 0.03255813953488372)

In [7]:
from polars import read_csv
TXs = read_csv('./data/txs_ext.csv')

Rates = DataFrame({
  'rate': [1.25],
  'timestamp': [0]
})

TodaysRate = DataFrame({
  'todays_rate': [1.24],
})

Res = TXs.join_asof(Rates, on='timestamp') \
  .join(TodaysRate, how="cross") \
  .sort(col('timestamp')) \
  .with_columns(
    price_base=col('price')/col('rate'),
  ).with_columns(
    cost_base=col('price_base')*col('quantity_ext'),
    value_base=col('value')/col('rate'),
    true_value_base=col('value')/col('todays_rate'),
  ).with_columns(
    fx_impact= col('true_value_base')-col('value_base')
  )

Res

shape: (69, 38)
┌─────┬──────────┬──────┬───────────┬───┬────────────┬────────────┬─────────────────┬───────────┐
│ id  ┆ asset_id ┆ type ┆ quantity  ┆ … ┆ cost_base  ┆ value_base ┆ true_value_base ┆ fx_impact │
│ --- ┆ ---      ┆ ---  ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---             ┆ ---       │
│ i64 ┆ i64      ┆ str  ┆ f64       ┆   ┆ f64        ┆ f64        ┆ f64             ┆ f64       │
╞═════╪══════════╪══════╪═══════════╪═══╪════════════╪════════════╪═════════════════╪═══════════╡
│ 383 ┆ 190      ┆ buy  ┆ 0.9540788 ┆ … ┆ 201.760952 ┆ 238.98529  ┆ 240.912591      ┆ 1.927301  │
│ 384 ┆ 190      ┆ buy  ┆ 0.2141335 ┆ … ┆ 45.276387  ┆ 53.637872  ┆ 54.070436       ┆ 0.432563  │
│ 385 ┆ 190      ┆ buy  ┆ 0.2334888 ┆ … ┆ 49.845189  ┆ 58.486143  ┆ 58.957805       ┆ 0.471662  │
│ 386 ┆ 190      ┆ buy  ┆ 0.742955  ┆ … ┆ 158.576315 ┆ 186.101312 ┆ 187.602129      ┆ 1.500817  │
│ 387 ┆ 190      ┆ buy  ┆ 1.2305533 ┆ … ┆ 254.212623 ┆ 308.238835 ┆ 310.724632      ┆ 2.485797  │
│ …   ┆ …        ┆ …    ┆ …         ┆ … ┆ …          ┆ …          ┆ …               ┆ …         │
│ 447 ┆ 190      ┆ buy  ┆ 0.436242  ┆ … ┆ 104.802829 ┆ 108.10431  ┆ 108.976119      ┆ 0.871809  │
│ 448 ┆ 190      ┆ buy  ┆ 2.495105  ┆ … ┆ 598.825243 ┆ 618.307024 ┆ 623.293371      ┆ 4.986347  │
│ 449 ┆ 190      ┆ buy  ┆ 0.288194  ┆ … ┆ 69.604634  ┆ 71.416799  ┆ 71.992741       ┆ 0.575942  │
│ 450 ┆ 190      ┆ buy  ┆ 0.240293  ┆ … ┆ 59.592592  ┆ 59.546456  ┆ 60.026669       ┆ 0.480213  │
│ 451 ┆ 190      ┆ sell ┆ 14.100621 ┆ … ┆ -3494.2468 ┆ 3494.2468  ┆ 3522.42621      ┆ 28.17941  │
└─────┴──────────┴──────┴───────────┴───┴────────────┴────────────┴─────────────────┴───────────┘

In [26]:
df0 = DataFrame({
  'ts': [],
  'price': []
}, schema={'ts':Int64, 'price':Int64})
df1 = DataFrame({
  'ts': [1,2,3],
  'price': [1,2,3]
})
df2 = DataFrame({
  'ts':[2,3,4],
  'price':[4,2,7]
})
df0.join(df1, on='ts', how='full', coalesce=True, suffix='2').sort(col('ts')).with_columns(
  price=col('price').backward_fill().forward_fill(),
  price2=col('price2').backward_fill().forward_fill(),
).select(
  col('ts'),
  price=col('price')+col('price2')
)

shape: (3, 2)
┌─────┬───────┐
│ ts  ┆ price │
│ --- ┆ ---   │
│ i64 ┆ i64   │
╞═════╪═══════╡
│ 1   ┆ null  │
│ 2   ┆ null  │
│ 3   ┆ null  │
└─────┴───────┘